### ISSUE TITLE
Simple File Browser - Click & Head Tracking

### ISSUE THREAD

**Issue by alitokur** [yasirkula/UnitySimpleFileBrowser#24]
**Description of the bug**

Dear Sir, 
I am using your "simple file browser" for my VR project. Actually, it's working well but there is something that I did not get it. 
I can select the files from the list but i cannot click them.  I can interact with all the buttons in my interface, but I cannot click the files in the file list. In addition, my oculus rift headset acting like a pointer when I'm on the file list panel. While I moving my head from up to down or vice versa I can select the files like my pointers. 

**Reproduction steps**

-changing the canvas render mode "overlay to wordspace.
- using oculus rift SDK with VRTK

**Platform specs**

- Unity version: * 2019.3.10*
- Platform: *Windows*
- How did you download the plugin: * Asset Store*

**Screenshot**
![ss](https://user-images.githubusercontent.com/20575896/95026324-41e19d80-0699-11eb-963c-03f641eeb03e.png)

**Comment by yasirkula** [comment]
By default, files are selected on double click. However, you can change this behaviour by setting FileBrowser.SingleClickMode to true.

**Comment by alitokur** [comment]
that is my bad. I ve disabled the button component. now it's working i can select the files. yet I don't understand why my headset acts as a pointer on the file list menu.

**Comment by yasirkula** [comment]
I haven't implemented any VR input modules for this plugin. Your headset SDK is probably causing the headset to act as a pointer for all UI objects, including FileBrowser.

**Comment by alitokur** [comment]
probably, thank you for the help sir 👍

**Comment by yaalisri** [comment]
Does this work for VR based Unity projects on iOS and Android? Is It possible to render the file picker in worldspace?

**Comment by yasirkula** [comment]
Since it's created with uGUI, of course! You can place the SimpleFileBrowserCanvas prefab to your scene, change its Canvas Render Mode, position it as you wish and at the beginning of the game (in your script's Start function), deactivate the file browser GameObject. SimpleFileBrowser will now use the SimpleFileBrowserCanvas instance in your scene.

**Comment by yvonneradke** [comment]
Hi!
I have a similar problem but can't seem to find the solution. I'm using the file browser with the meta quest 3 and hand tracking. The hand tracking is done with the Meta XR Interaction SDK. I can click all the buttons and the quick links on the left side of the panel but I cannot interact with the files and folders shown in the right side of the panel at all. Any ideas as to why this happens?

**Comment by yasirkula** [comment]
@yvonneradke There are nested GraphicRaycasters in SimpleFileBrowserCanvas. Do you need to change them to work with Meta XR SDK?

**Comment by yvonneradke** [comment]
I already deleted the GraphicRaycaster and added a Tracked Device Graphic Raycaster. Since it's working for most of the canvas (expect for the middle right part) I assumed that I might need to change something in the code for this area.

**Comment by yvonneradke** [comment]
@yasirkula Sorry to bother you again, but I stumbled upon another problem. I want to use the file browser to open obj files. The problem is that the obj loader needs raw path data, which is not given when I am using SAF, but if I set shouldUseSAF to false, my obj data is not displayed anymore and I cannot select it. Do you have a solution to this problem?
