### ISSUE TITLE
Images Thumbnails

### ISSUE THREAD

**Issue by pdolgoter** [yasirkula/UnitySimpleFileBrowser#53]
How to display images thumbnails instead of nice icons that exist now so the user can see what he is choosing from?

**Comment by yasirkula** [comment]
SimpleFileBrowser doesn't have that functionality built-in since it requires implementing a texture caching system, which can be really complex. To implement this feature on your own, you can modify either [this code](https://github.com/yasirkula/UnitySimpleFileBrowser/blob/a4baa2cace37e8b8ef0037a0a5061f3e867fd076/Assets/Plugins/SimpleFileBrowser/Scripts/FileBrowserItem.cs#L53-L59) or [this code](https://github.com/yasirkula/UnitySimpleFileBrowser/blob/a4baa2cace37e8b8ef0037a0a5061f3e867fd076/Assets/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L545-L546).

**Comment by pdolgoter** [comment]
Thank you for the quick reply! Appreciate the work you've done here.
