### ISSUE TITLE
Getting FileBrowser instance

### ISSUE THREAD

**Issue by shyamnair3** [yasirkula/UnitySimpleFileBrowser#65]
Hi,

How to access the FileBrowser instance to change transform,canvas, etc. at runtime?

**Comment by yasirkula** [comment]
Hi, you can change Instance's visibility to public (it's private because the file browser is supposed to be used via its static functions and users might get confused about whether or not to use Instance after seeing it in Intellisense): https://github.com/yasirkula/UnitySimpleFileBrowser/blob/bb487817ad4656d19d1e67d5375782531b7e8cb1/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L331

Or you can put the FileBrowser to your scene, assign it to a public variable, deactivate it in Awake/Start and then modify it as you wish.

**Comment by shyamnair3** [comment]
Thank you for the quick response
